#!/usr/bin/env bash
# =============================================================================
#  bob_run.sh — Bob-A-Thon Master Orchestration Script
#  IBM Bob × Developer Kaki Hackathon
#
#  PURPOSE
#  -------
#  End-to-end demonstration script that:
#    1. Scaffolds the GitHub repository
#    2. Invokes IBM Bob (Agent Mode) to generate each core artefact
#    3. Starts the Prometheus exporter
#    4. Verifies the Grafana datasource is reachable
#    5. Commits and pushes everything to the remote
#
#  PREREQUISITES
#  -------------
#    - IBM Bob CLI installed and authenticated  (bob --version)
#    - Python 3.10+                             (python --version)
#    - pip packages: prometheus_client          (pip install prometheus_client)
#    - Git configured with SSH/HTTPS access to the remote
#    - Grafana instance reachable at $GRAFANA_URL (default: http://localhost:3000)
#    - Prometheus instance reachable at $PROMETHEUS_URL
#
#  USAGE
#  -----
#    chmod +x bob_run.sh
#    ./bob_run.sh
#
#  ENV OVERRIDES
#    GITHUB_REMOTE   — remote URL           (default: https://github.com/ctin0018/Bob-A-Thon.git)
#    GRAFANA_URL     — Grafana base URL     (default: http://localhost:3000)
#    GRAFANA_API_KEY — Grafana service token (required for dashboard import)
#    PROMETHEUS_URL  — Prometheus base URL  (default: http://localhost:9090)
#    EXPORTER_PORT   — metrics port         (default: 8000)
# =============================================================================

set -euo pipefail

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
GITHUB_REMOTE="${GITHUB_REMOTE:-https://github.com/ctin0018/Bob-A-Thon.git}"
GRAFANA_URL="${GRAFANA_URL:-http://localhost:3000}"
GRAFANA_API_KEY="${GRAFANA_API_KEY:-}"
PROMETHEUS_URL="${PROMETHEUS_URL:-http://localhost:9090}"
EXPORTER_PORT="${EXPORTER_PORT:-8000}"
REPO_DIR="Bob-A-Thon"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'

log()  { echo -e "${CYAN}[BOB-A-THON]${NC} $*"; }
ok()   { echo -e "${GREEN}[  OK  ]${NC} $*"; }
warn() { echo -e "${YELLOW}[ WARN ]${NC} $*"; }
fail() { echo -e "${RED}[ FAIL ]${NC} $*"; exit 1; }

# ---------------------------------------------------------------------------
# 0. Dependency checks
# ---------------------------------------------------------------------------
log "Checking prerequisites …"
command -v bob     >/dev/null 2>&1 || fail "IBM Bob CLI not found. Install from https://www.ibm.com/products/watsonx-code-assistant"
command -v python3 >/dev/null 2>&1 || fail "Python 3 not found."
command -v git     >/dev/null 2>&1 || fail "Git not found."
ok "All prerequisites satisfied."

# ---------------------------------------------------------------------------
# 1. Scaffold GitHub Repository
# ---------------------------------------------------------------------------
log "Scaffolding repository …"
if [ ! -d "$REPO_DIR" ]; then
  mkdir "$REPO_DIR"
fi
cd "$REPO_DIR"

if [ ! -d ".git" ]; then
  git init
  git branch -M main
  git remote add origin "$GITHUB_REMOTE"
  ok "Git repository initialised."
else
  ok "Git repository already exists — skipping init."
fi

# ---------------------------------------------------------------------------
# 2. IBM Bob — Generate scanner.py
# ---------------------------------------------------------------------------
log "Invoking IBM Bob: generating scanner.py …"
bob agent \
  "Write a Python module called scanner.py that scans log files or raw strings \
for Malaysian NRICs (format YYMMDD-SS-NNNN) and PCI credit card numbers. \
Expose a scan_line(), scan_file(), and scan_text() function. \
Return structured PIIFinding dataclass objects. \
Include a _mask() helper that redacts NRIC to YYMMDD-**-**** and credit cards to ****-****-****-LAST4."
ok "scanner.py generated by IBM Bob."

# ---------------------------------------------------------------------------
# 3. IBM Bob — Generate sanitizer.py
# ---------------------------------------------------------------------------
log "Invoking IBM Bob: generating sanitizer.py …"
bob agent \
  "Write a Python logging.Filter subclass called PIISanitizingFilter in sanitizer.py. \
The filter must intercept log records at runtime, apply regex substitution to mask \
Malaysian NRICs and PCI credit card numbers before they are written to any handler, \
and increment a prometheus_client Counter named pii_log_interceptions_total with a \
pii_type label. Include an install_global_filter() convenience function."
ok "sanitizer.py generated by IBM Bob."

# ---------------------------------------------------------------------------
# 4. IBM Bob — Generate exporter.py
# ---------------------------------------------------------------------------
log "Invoking IBM Bob: generating exporter.py …"
bob agent \
  "Write a Prometheus metrics exporter in exporter.py. \
Run a lightweight WSGI HTTP server on port 8000 exposing /metrics and /healthz. \
Define these metrics: \
  pii_log_interceptions_total (Counter, label: pii_type), \
  pii_scan_duration_seconds (Histogram), \
  pii_active_scanner_info (Gauge with version and environment labels). \
Pre-initialise NRIC and CREDIT_CARD label series so dashboards show zero before first event. \
Include a start_exporter(port, daemon) function and a __main__ CLI entry-point."
ok "exporter.py generated by IBM Bob."

# ---------------------------------------------------------------------------
# 5. IBM Bob — Generate Grafana dashboard PromQL expressions
# ---------------------------------------------------------------------------
log "Invoking IBM Bob: generating Grafana PromQL expressions and dashboard …"
bob agent \
  "Generate the PromQL expressions for the following Grafana dashboard panels for a \
PII Log Leak Detector Prometheus exporter: \
  Panel 1 — Total PII Breaches Prevented (Stat): sum(pii_log_interceptions_total) \
  Panel 2 — NRIC Tokens Masked (Stat): pii_log_interceptions_total{pii_type='NRIC'} \
  Panel 3 — Credit Card Tokens Masked (Stat): pii_log_interceptions_total{pii_type='CREDIT_CARD'} \
  Panel 4 — Developer Hours Saved (Stat, estimate @ 0.05h/event): sum(pii_log_interceptions_total) * 0.05 \
  Panel 5 — Interceptions per Minute (Time series): rate(pii_log_interceptions_total[1m]) * 60 \
  Panel 6 — Pie chart breakdown: pii_log_interceptions_total by pii_type \
  Panel 7 — p50 scan latency (Gauge): histogram_quantile(0.50, sum(rate(pii_scan_duration_seconds_bucket[5m])) by (le)) \
  Panel 8 — p99 scan latency (Gauge): histogram_quantile(0.99, sum(rate(pii_scan_duration_seconds_bucket[5m])) by (le)) \
Then produce a complete Grafana dashboard JSON model saved as grafana/dashboard.json \
with uid 'bob-a-thon-pii-v1', timezone 'Asia/Kuala_Lumpur', and refresh interval 10s."
ok "grafana/dashboard.json generated by IBM Bob."

# ---------------------------------------------------------------------------
# 6. Install Python dependencies
# ---------------------------------------------------------------------------
log "Installing Python dependencies …"
python3 -m pip install --quiet prometheus_client
ok "prometheus_client installed."

# ---------------------------------------------------------------------------
# 7. Start the Prometheus Metrics Exporter (background)
# ---------------------------------------------------------------------------
log "Starting PII metrics exporter on port ${EXPORTER_PORT} …"
EXPORTER_PORT="$EXPORTER_PORT" python3 exporter.py &
EXPORTER_PID=$!
sleep 2

if kill -0 "$EXPORTER_PID" 2>/dev/null; then
  ok "Exporter running (PID ${EXPORTER_PID}). Scrape: http://localhost:${EXPORTER_PORT}/metrics"
else
  fail "Exporter failed to start. Check exporter.py."
fi

# ---------------------------------------------------------------------------
# 8. Verify Prometheus can reach the exporter
# ---------------------------------------------------------------------------
log "Verifying /metrics endpoint …"
HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:${EXPORTER_PORT}/metrics" || echo "000")
if [ "$HTTP_STATUS" = "200" ]; then
  ok "/metrics endpoint returned 200."
else
  warn "/metrics returned HTTP ${HTTP_STATUS} — check firewall or port conflicts."
fi

# ---------------------------------------------------------------------------
# 9. Import Grafana Dashboard (requires GRAFANA_API_KEY)
# ---------------------------------------------------------------------------
if [ -n "$GRAFANA_API_KEY" ]; then
  log "Importing dashboard into Grafana at ${GRAFANA_URL} …"
  DASHBOARD_PAYLOAD=$(python3 -c "
import json, sys
with open('grafana/dashboard.json') as f:
    d = json.load(f)
d.pop('id', None)
print(json.dumps({'dashboard': d, 'overwrite': True, 'folderId': 0}))
")
  IMPORT_STATUS=$(curl -s -o /tmp/grafana_import.json -w "%{http_code}" \
    -X POST "${GRAFANA_URL}/api/dashboards/import" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer ${GRAFANA_API_KEY}" \
    -d "$DASHBOARD_PAYLOAD")

  if [ "$IMPORT_STATUS" = "200" ]; then
    DASHBOARD_URL=$(python3 -c "import json; d=json.load(open('/tmp/grafana_import.json')); print(d.get('importedUrl',''))" 2>/dev/null || echo "")
    ok "Dashboard imported: ${GRAFANA_URL}${DASHBOARD_URL}"
  else
    warn "Grafana import returned HTTP ${IMPORT_STATUS}. Check GRAFANA_API_KEY and GRAFANA_URL."
    cat /tmp/grafana_import.json
  fi
else
  warn "GRAFANA_API_KEY not set — skipping automatic dashboard import."
  log "To import manually: Grafana → Dashboards → Import → Upload grafana/dashboard.json"
fi

# ---------------------------------------------------------------------------
# 10. Commit all artefacts and push to GitHub
# ---------------------------------------------------------------------------
log "Committing artefacts …"
git add .

if ! git diff --cached --quiet; then
  git commit -m "feat: IBM Bob-generated PII scanner, masking filter, Prometheus exporter, and Grafana dashboard

Co-authored-by: IBM Bob <ibmbob@ibm.com>

- scanner.py   : detects Malaysian NRICs and PCI credit card numbers in log streams
- sanitizer.py : logging.Filter that masks PII before any handler writes to disk
- exporter.py  : Prometheus metrics exporter on :8000/metrics
- grafana/dashboard.json : Business Observability North Star KPI dashboard

Compliance coverage: BNM RMIT, PDPA
North Star Metrics  : Total PII Breaches Prevented, Developer Hours Saved"
  git push -u origin main
  ok "Pushed to ${GITHUB_REMOTE}"
else
  ok "Nothing new to commit — repository is up to date."
fi

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║       Bob-A-Thon — Deployment Complete 🎉                    ║${NC}"
echo -e "${GREEN}╠══════════════════════════════════════════════════════════════╣${NC}"
echo -e "${GREEN}║  Prometheus scrape : http://localhost:${EXPORTER_PORT}/metrics          ║${NC}"
echo -e "${GREEN}║  Health check      : http://localhost:${EXPORTER_PORT}/healthz          ║${NC}"
echo -e "${GREEN}║  Grafana dashboard : ${GRAFANA_URL}/d/bob-a-thon-pii-v1   ║${NC}"
echo -e "${GREEN}║  GitHub repo       : ${GITHUB_REMOTE}                   ║${NC}"
echo -e "${GREEN}╠══════════════════════════════════════════════════════════════╣${NC}"
echo -e "${GREEN}║  North Star KPIs (live in Grafana):                          ║${NC}"
echo -e "${GREEN}║    • Total PII Breaches Prevented                            ║${NC}"
echo -e "${GREEN}║    • NRIC Tokens Masked                                      ║${NC}"
echo -e "${GREEN}║    • Credit Card Tokens Masked                               ║${NC}"
echo -e "${GREEN}║    • Developer Hours Saved (est.)                            ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════════════════╝${NC}"
